apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference
  namespace: soc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-inference
  template:
    metadata:
      labels:
        app: ai-inference
        zarf.dev/agent: skip
    spec:
      initContainers:
      - name: preflight-cookbook
        image: phoenixvlabs/nexus-ai-inference:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "preflight.py"]
        volumeMounts:
        - name: models-volume
          mountPath: /models
      containers:
      - name: ai-inference
        securityContext:
          allowPrivilegeEscalation: false
        image: phoenixvlabs/nexus-ai-inference:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: models-volume
          mountPath: /models
        ports:
        - containerPort: 8000
          name: api
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "250m"
            memory: 256Mi
      volumes:
      - name: models-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ai-inference
  namespace: soc
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: api
  selector:
    app: ai-inference
