apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ai-inference.yaml
  - nexus-workbench.yaml
  - nexus-athena.yaml
  - nexus-athena-elevated.yaml
  - vault.yaml
  - github.com/acald-creator/nexus-webtop-soc/deploy/kubernetes/base
