apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-athena
  namespace: soc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-athena
  template:
    metadata:
      labels:
        app: nexus-athena
        zarf.dev/agent: skip
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: nexus-athena
        image: local/nexus-athena:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: athena-home
          mountPath: /home/kali
      volumes:
      - name: athena-home
        persistentVolumeClaim:
          claimName: nexus-athena-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-athena-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-athena
  namespace: soc
spec:
  ports:
  - port: 22
    targetPort: 22
    name: ssh
  selector:
    app: nexus-athena
