apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: soc
spec:
  serviceName: wazuh-indexer
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
        zarf.dev/agent: skip
    spec:
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.7.5
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: api
        env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "admin"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        volumeMounts:
        - name: wazuh-indexer-data
          mountPath: /usr/share/wazuh-indexer/data
  volumeClaimTemplates:
  - metadata:
      name: wazuh-indexer-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: soc
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: api
  selector:
    app: wazuh-indexer
