$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: soc
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: soc
---
$patch: delete
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-server-config
  namespace: soc
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  namespace: soc
