apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: prod-patch.yaml
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vault
    target:
      kind: Deployment
      name: vault
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: vault
    target:
      kind: Service
      name: vault
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: minio
    target:
      kind: StatefulSet
      name: minio
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: minio
    target:
      kind: Service
      name: minio

helmGlobals:
  chartHome: /tmp/charts

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.28.0
    releaseName: vault
    namespace: soc
    valuesFile: vault-values.yaml
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 14.6.0
    releaseName: minio
    namespace: soc
    valuesFile: minio-values.yaml
