apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: soc
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
  namespace: soc
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: soc
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: vault
        command: ["vault", "server", "-config=/vault/config/vault.hcl"]
