version: '3.8'

services:
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.5
    hostname: wazuh.indexer
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - wazuh-indexer-data:/usr/share/wazuh-indexer/data
    networks:
      - soc-net

  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.5
    hostname: wazuh.manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - WAZUH_API_USER=admin
      - WAZUH_API_PASSWORD=admin
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - wazuh-manager-etc:/var/ossec/etc
      - wazuh-manager-logs:/var/ossec/logs
      - suricata-logs:/var/log/suricata
    networks:
      - soc-net
    depends_on:
      - wazuh.indexer

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.5
    hostname: wazuh.dashboard
    ports:
      - "5601:5601"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - WAZUH_API_URL=https://wazuh.manager:55000
      - SERVER_SSL_ENABLED=false
    networks:
      - soc-net
    depends_on:
      - wazuh.indexer
      - wazuh.manager

  suricata.sensor:
    image: jasonish/suricata:7.0
    hostname: suricata.sensor
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    networks:
      - soc-net
    volumes:
      - suricata-logs:/var/log/suricata
    command: -i eth0

  webtop.analyst:
    build:
      context: ../../../nexus-webtop-soc
      dockerfile: Dockerfile
      args:
        VARIANT: xfce
    image: phoenixvlabs/nexus-webtop-soc:amd64-latest
    hostname: webtop.analyst
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3000:3000"
    volumes:
      - webtop-analyst-config:/config
      - soc-shared:/soc-shared
    networks:
      - soc-net
    shm_size: "1gb"

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  wazuh-manager-etc:
  wazuh-manager-logs:
  suricata-logs:
  webtop-analyst-config:
  soc-shared:

networks:
  soc-net:
    driver: bridge
